# Generated by Django 5.2 on 2025-04-16 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CATEGORY',
            fields=[
                ('cod_category', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='USER',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=128)),
                ('name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=20)),
                ('born_date', models.DateField()),
                ('adress', models.CharField(blank=True, max_length=200, null=True)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='fotos_perfil/')),
            ],
        ),
        migrations.CreateModel(
            name='GAME',
            fields=[
                ('cod_game', models.AutoField(primary_key=True, serialize=False)),
                ('game_name', models.CharField(max_length=100)),
                ('game_description', models.TextField()),
                ('game_price', models.IntegerField()),
                ('game_picture', models.ImageField(upload_to='caratulas/')),
                ('cod_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.category')),
            ],
        ),
    ]
