# Generated by Django 5.2 on 2025-04-18 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='rol',
            field=models.IntegerField(choices=[(1, 'Usuario'), (2, 'Administrador')], default=1),
        ),
    ]
